# This file was generated by anodizer (https://github.com/tj-smith47/anodizer). DO NOT EDIT.
cask "anodizer" do
  version "0.28.0"
  homepage "https://github.com/tj-smith47/anodizer"
  name "anodizer"
  desc "A Rust-native release automation tool"

  livecheck do
    url :url
    strategy :github_latest
  end

  on_linux do
    on_arm do
      sha256 "a7161f396d280740c7ee81842cdfafbcc218fa9becd49b41e722c534b63459da"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "d924bb7ee95b4cece3a31311048e306215c6f57ab9ed5c94824e574bce4827f4"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-linux-amd64.tar.gz"
    end
  end

  on_macos do
    on_arm do
      sha256 "a74bde9a9b89092802e8e79725ec211a2031c0e4036fab0864aa1d1ebdb34f89"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "b6fc2539ca29b8b228b0a2549b798802f196bf46099dd518261e9bd4b4bc7470"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-darwin-amd64.tar.gz"
    end
  end

  depends_on formula: "git"
  binary "anodizer"
  manpage "anodizer.1"

  generate_completions_from_executable "anodizer", "completion",
    base_name: "anodizer",
    shells: [:bash, :zsh, :fish]

  caveats <<~EOS
    Run `anodizer init` to scaffold a config in your repo.

  EOS
end
