# This file was generated by anodizer. DO NOT EDIT.
cask "anodizer" do
  version "0.15.4"
  homepage "https://github.com/tj-smith47/anodizer"
  name "anodizer"
  desc "A Rust-native release automation tool"

  livecheck do
    url :url
    strategy :github_latest
  end

  on_linux do
    on_arm do
      sha256 "46f97dcf97a09a7fafcb523d2edd5fde71a3a24b1d512c542d99a6dfe7946c8c"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-linux-arm64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
    on_intel do
      sha256 "faae05435650f60cc8804d26502a480aff052e2a9256632d7f89cf04c36015bd"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-linux-amd64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
  end

  on_macos do
    on_arm do
      sha256 "f1a50b0b23e3e1e95bd60244c50677f795416527e97c757b4ecd0c21f87891f0"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
    on_intel do
      sha256 "4838c129733b08cfd2f69ceef9fbf8b92b6c96c0308b4d58cc32cb4dbb39a8be"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
  end

  depends_on formula: "git"
  binary "anodizer"
  manpage "anodizer.1"

  generate_completions_from_executable "anodizer", "completion",
    base_name: "anodizer",
    shells: [:bash, :zsh, :fish]

  caveats <<~EOS
    Run `anodizer init` to scaffold a config in your repo.

  EOS
end
