# This file was generated by anodizer. DO NOT EDIT.
cask "anodizer" do
  version "0.15.2"
  homepage "https://github.com/tj-smith47/anodizer"
  name "anodizer"
  desc "A Rust-native release automation tool"

  livecheck do
    url :url
    strategy :github_latest
  end

  on_linux do
    on_arm do
      sha256 "b4463c6c8a79df112a461ee25fcd837c458a081b56de9f0d37ff2b6f4cff6d4b"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-linux-arm64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
    on_intel do
      sha256 "caec2e15a7325e444b360bf0bf18881056ba56b59da4bd0556bc42172e80da1c"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-linux-amd64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
  end

  on_macos do
    on_arm do
      sha256 "daa2158484dd6e12b06599e82855d2cbe7a81606d77b785f718a33de1b5ee63c"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
    on_intel do
      sha256 "ac6d7b0521897be2e43947053aea50c805d43f80a2222f61c5d99cb63ee80c31"
      url "https://github.com/tj-smith47/anodizer/releases/download/v#{version}/anodizer-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/tj-smith47/anodizer/releases/download"
    end
  end

  depends_on formula: "git"
  binary "anodizer"
  manpage "anodizer.1"

  generate_completions_from_executable "anodizer", "completion",
    base_name: "anodizer",
    shells: [:bash, :zsh, :fish]

  caveats <<~EOS
    Run `anodizer init` to scaffold a config in your repo.

  EOS
end
