# This file was generated by anodizer (https://github.com/tj-smith47/anodizer). DO NOT EDIT.
cask "cfgd" do
  version "0.7.0"
  homepage "https://github.com/tj-smith47/cfgd"
  name "cfgd"
  desc "Declarative, GitOps-style machine configuration management"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_linux do
    on_arm do
      sha256 "cfc7786a248c8adde5648e86e27f660190978b05beba58e8cc53171a904f81e5"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "5f72415938f88c8ebf76e2e5c936350cd52d1294ec12150aabbc0ad32c2db380"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-linux-amd64.tar.gz"
    end
  end

  on_macos do
    on_arm do
      sha256 "a33182560ae656826a08e4f07744f468c0e502cc156c7f99f3b0d275f22af0f3"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "3fbd163f4b0ae316536bb3f77ccb5592cf7d435dbfa68ac856c77eef4a723a4f"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-darwin-amd64.tar.gz"
    end
  end

  depends_on formula: "git"
  binary "cfgd"
  manpage "man/man1/cfgd.1"

  generate_completions_from_executable "cfgd", "completion",
    base_name: "cfgd"

  caveats <<~EOS
    Run `cfgd init` to scaffold a config in your repo.

  EOS
end
