# This file was generated by anodizer (https://github.com/tj-smith47/anodizer). DO NOT EDIT.
cask "cfgd" do
  version "0.6.2"
  homepage "https://github.com/tj-smith47/cfgd"
  name "cfgd"
  desc "Declarative, GitOps-style machine configuration management"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_linux do
    on_arm do
      sha256 "410ba7e393ee6d1c5068d169644c814239f5b04a85d2f33fa5a5f26189053b7e"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "7a791fd9c70717a734b47bcd1f5e6072e539ca7d5ae60b918c42225ddafc7421"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-linux-amd64.tar.gz"
    end
  end

  on_macos do
    on_arm do
      sha256 "9bc2c855e7761616cee9768d761bcb7d00bd1ebf6a3114f2559677eb17289a4d"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "b8be4e09dc57809cefd97c3026fe164b64054b3f773d766a3f2f55e7b92f4357"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-darwin-amd64.tar.gz"
    end
  end

  depends_on formula: "git"
  binary "cfgd"
  manpage "man/man1/cfgd.1"

  generate_completions_from_executable "cfgd", "completion",
    base_name: "cfgd"

  caveats <<~EOS
    Run `cfgd init` to scaffold a config in your repo.

  EOS
end
