# This file was generated by anodizer (https://github.com/tj-smith47/anodizer). DO NOT EDIT.
cask "cfgd" do
  version "0.8.0"
  homepage "https://github.com/tj-smith47/cfgd"
  name "cfgd"
  desc "Declarative, GitOps-style machine configuration management"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_linux do
    on_arm do
      sha256 "ffde99c8ff524fa0102f149d98d086d7531d879f3db2f53a70646932a9d04b6c"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "ecd4b2923b6046a819f373511d9d1b199a96b58704c0396f899d82ae8721b011"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-linux-amd64.tar.gz"
    end
  end

  on_macos do
    on_arm do
      sha256 "d80bdd535591e064afbdac8d8a67c1b071cb33d832bbe8c2589fff7aa805d2d1"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "f511d4cb70c127fd7332dc542770d4740e5e4bf9f00ab8d7bb6993fdd7d55746"
      url "https://github.com/tj-smith47/cfgd/releases/download/v#{version}/cfgd-#{version}-darwin-amd64.tar.gz"
    end
  end

  depends_on formula: "git"
  binary "cfgd"
  manpage "man/man1/cfgd.1"

  generate_completions_from_executable "cfgd", "completion",
    base_name: "cfgd"

  caveats <<~EOS
    Run `cfgd init` to scaffold a config in your repo.

  EOS
end
