# This file was generated by anodizer. DO NOT EDIT.
# typed: false
# frozen_string_literal: true

class Anodizer < Formula
  desc "A Rust-native release automation tool"
  homepage "https://github.com/tj-smith47/anodizer"
  license "MIT"

  version "0.1.1"

  # platform: x86_64-pc-windows-msvc
  url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.1/anodizer-0.1.1-windows-amd64.zip"

  sha256 "d0177ea8564f6e33a971ab54097fb9efe07eb4bb81e9e3ad535801c0b96bb77c"
  # platform: aarch64-pc-windows-msvc
  url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.1/anodizer-0.1.1-windows-arm64.zip"

  sha256 "acd051e0692e545a26e406f51795da922210efa5183d5c862a75c2f3634ec051"
  on_macos do
    on_intel do
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.1/anodizer-0.1.1-darwin-amd64.tar.gz"

      sha256 "c2c7eb77bef8320ed4211f5caae0cf36a9928bf9e5e60f04c255a5ccf3c3631c"

      def install
        bin.install "anodizer"
      end
    end
    on_arm do
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.1/anodizer-0.1.1-darwin-arm64.tar.gz"

      sha256 "a7d9485aa95a71ae8b6733493f40e157d90ded0172fe24997966adc9738ac42e"

      def install
        bin.install "anodizer"
      end
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.1/anodizer-0.1.1-linux-arm64.tar.gz"

      sha256 "e414ee6801fcd92090c21946fe2cd32d4317397e6fb766fba22c7bdf69959220"

      def install
        bin.install "anodizer"
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.1/anodizer-0.1.1-linux-amd64.tar.gz"

      sha256 "61e123af6ab72827d1592f692008a7efc99caa982440ec0d29d96fb3d653c0ba"

      def install
        bin.install "anodizer"
      end
    end
  end

  test do
    system "#{bin}/anodizer", "--version"
  end
end
