# This file was generated by anodizer. DO NOT EDIT.
# typed: false
# frozen_string_literal: true

class Anodizer < Formula
  desc "A Rust-native release automation tool"
  homepage "https://github.com/tj-smith47/anodizer"
  license "MIT"

  version "0.1.0"

  # platform: x86_64-pc-windows-msvc
  url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.0/anodizer-0.1.0-windows-amd64.zip"

  sha256 "21211f7fe46e453cf03ab143bf90f896d7844c29baddb309fe93b66bb1a42516"
  # platform: aarch64-pc-windows-msvc
  url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.0/anodizer-0.1.0-windows-arm64.zip"

  sha256 "e13926f7c0515edfa47b237050e439ad3e5ad255bfec8487f9442d0363997088"
  on_macos do
    on_arm do
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.0/anodizer-0.1.0-darwin-arm64.tar.gz"

      sha256 "393061f5369424efe8a5f3ac9cc36d94b5b3bced6e13921eb0c298813e8f3609"

      def install
        bin.install "anodizer"
      end
    end
    on_intel do
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.0/anodizer-0.1.0-darwin-amd64.tar.gz"

      sha256 "e7be3c26dcc56e04fbaec9fdeae1b903162a12b1f81123c817d16f675109b28b"

      def install
        bin.install "anodizer"
      end
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.0/anodizer-0.1.0-linux-arm64.tar.gz"

      sha256 "d77ba13c3a3608dc0520a3d9ff16b4a9dc12a9fcb78fd0ca0797a5174e78b97f"

      def install
        bin.install "anodizer"
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/anodizer/releases/download/v0.1.0/anodizer-0.1.0-linux-amd64.tar.gz"

      sha256 "6f1572971cd86ca892fb0d00981b4300717d4ab29d470fa6dae86e89fe86c19f"

      def install
        bin.install "anodizer"
      end
    end
  end

  test do
    system "#{bin}/anodizer", "--version"
  end
end
