# This file was generated by anodizer. DO NOT EDIT.
# typed: false
# frozen_string_literal: true

class Cfgd < Formula
  desc "Declarative, GitOps-style machine configuration management"
  homepage "https://github.com/tj-smith47/cfgd"
  license "MIT"

  version "0.3.5"

  # platform: aarch64-pc-windows-msvc
  url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-windows-arm64.zip"

  sha256 "db86d0aacf36bafe0d2da2e0871744df59dd3898aabebfb1102a5fafe87160c8"
  # platform: x86_64-pc-windows-msvc
  url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-windows-amd64.zip"

  sha256 "8e64bbe1763f69442cf2cfffbae9f40c7e5827dd0f7d5dc66e302fb81c22a0e9"
  on_macos do
    on_arm do
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-darwin-arm64.tar.gz"

      sha256 "ba997d73e298f0ab1309d7326191d89d01d009a61e5b638438427a4a0c0c2fb9"

      def install
        bin.install "cfgd"
      end
    end
    on_intel do
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-darwin-amd64.tar.gz"

      sha256 "a42c5dbac83dec26e768fb19b9e40f653bb0e27fa2773e18736b2e4c41cb17f7"

      def install
        bin.install "cfgd"
      end
    end
  end
  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-linux-amd64.tar.gz"

      sha256 "6aa4e1d1a02f9c8f456f888bf3ec797aadefd3f03f4cbc2601629896ffde8f01"

      def install
        bin.install "cfgd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-linux-arm64.tar.gz"

      sha256 "43acff5024659b4e4b86623b23c64d95a2c48e122f0efc6dacd18bbb963f9395"

      def install
        bin.install "cfgd"
      end
    end
  end

  test do
    system "#{bin}/cfgd", "--version"
  end
end
