# This file was generated by anodize. DO NOT EDIT.
# typed: false
# frozen_string_literal: true

class Cfgd < Formula
  desc "Declarative, GitOps-style machine configuration management"
  homepage "https://github.com/tj-smith47/cfgd"
  license "MIT"

  version "0.3.3"


  def install
    bin.install "cfgd"
  end

  test do
    system "#{bin}/cfgd", "--version"
  end
end
