# This file was generated by anodizer. DO NOT EDIT.
# typed: false
# frozen_string_literal: true

class Cfgd < Formula
  desc "Declarative, GitOps-style machine configuration management"
  homepage "https://github.com/tj-smith47/cfgd"
  license "MIT"

  version "0.3.5"

  # platform: x86_64-pc-windows-msvc
  url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-windows-amd64.zip"

  sha256 "fcc305a85fb9835e9dc5472af7025f086b5435cdf1a741f88f6d755990a5e86e"
  # platform: aarch64-pc-windows-msvc
  url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-windows-arm64.zip"

  sha256 "60f912d01d599e5edd72b6db8bd500cc62c8cd86e61ca0fb647b51144ab5307b"
  on_macos do
    on_arm do
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-darwin-arm64.tar.gz"

      sha256 "03ed24f91b3bdbd9c25b1d895be167b75ad55db8ff48e3a5cceb71fa6a06601f"

      def install
        bin.install "cfgd"
      end
    end
    on_intel do
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-darwin-amd64.tar.gz"

      sha256 "6a05a5c74db422d08191b629e15bfaa767d6d31f0005793c8ce4112127281ec8"

      def install
        bin.install "cfgd"
      end
    end
  end
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-linux-arm64.tar.gz"

      sha256 "be67677b54c7344856e8b654ac6f6365cfd6007818427a1e2250bddb534454a3"

      def install
        bin.install "cfgd"
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-smith47/cfgd/releases/download/v0.3.5/cfgd-0.3.5-linux-amd64.tar.gz"

      sha256 "e8b15186e209646fdccac5d3385bc7eca9b575a2a38e2eb510ef11028b9804b8"

      def install
        bin.install "cfgd"
      end
    end
  end

  test do
    system "#{bin}/cfgd", "--version"
  end
end
